### PR TITLE
(fix/global_ui)

### LINKED ISSUE #195: update global ui
**Describe the bug**
Some problems on global ui

- [x] Change progress bar color

- [x] Center "Delete" or "Check" container

- [x] Change small image from openfoodfact

- [x] Change small textfield in itemPage on big textfield

- [x] Center quantity 

- [x] Must see Units

- [x] Delete padding on share step 1

- [x] Delete padding on wishlist

### PR DESCRIPTION
**Pull request by zohra051**

### CODE REVIEW

File: lib/utility/curvePainter.dart [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+  static const Color color17 = Color(0xff8FCACA);
+  static const Color color18 = Color(0xffCCE2CB);
+  static const Color color19 = Color(0xffB6CFB6);
+  static const Color color20 = Color(0xff97C1A9);
+
+  static const Color color21 = Color(0xffFCB9AA);
+  static const Color color22 = Color(0xffFFDBCC);
+  static const Color color23 = Color(0xffECEAE4);
+  static const Color color24 = Color(0xffA2E1DB);
+  static const Color color25 = Color(0xff55CBCD);
```
Comment (nathanvandeperre97) [inline lib/utility/curvePainter.dart]: Why don't you generate a random color ?

**Review by nathanvandeperre97 — APPROVED** [review]
