### PR TITLE
Fixed : #346

### LINKED ISSUE #346: Item creation bug
**Describe the bug**
When the user try to create an item an set a property the rest of the item is reset

**To Reproduce**
1. Go to item creation page
2. Set a property
3. Set another property

**Expected behavior**
The user should be able to create items with the good properties

### PR DESCRIPTION
**Pull request by nathanvandeperre97**

### CODE REVIEW

File: lib/pages/items_page.dart [hunk 1]
```diff
@@ -323,6 +327,9 @@ class EditItemPageState extends State<EditItemPage> {
     provider.updateItemInList();
 
     FocusScope.of(context).unfocus();
+    GetIt.I.isRegistered<WishlistItemProvider>()
```
Comment (PiotrFLEURY) [inline lib/pages/items_page.dart]: don't do that. Register in main please

File: lib/pages/items_page.dart [hunk 2]
```diff
@@ -332,6 +339,9 @@ class EditItemPageState extends State<EditItemPage> {
     await provider.addItemTolist();
 
     FocusScope.of(context).unfocus();
+    GetIt.I.isRegistered<WishlistItemProvider>()
```
Comment (PiotrFLEURY) [inline lib/pages/items_page.dart]: don't do that. Register in main please

File: lib/pages/items_page.dart [hunk 3]
```diff
@@ -367,6 +377,9 @@ class EditItemPageState extends State<EditItemPage> {
   }
 
   goToPreviousPage() {
+    GetIt.I.isRegistered<WishlistItemProvider>()
```
Comment (PiotrFLEURY) [inline lib/pages/items_page.dart]: don't do that. Register in main please

File: lib/pages/items_page.dart [hunk 4]
```diff
@@ -61,8 +61,12 @@ class EditItemPageState extends State<EditItemPage> {
   @override
   Widget build(BuildContext context) {
     _args = Arguments.value(context);
+    GetIt.I.isRegistered<WishlistItemProvider>()
```
Comment (PiotrFLEURY) [inline lib/pages/items_page.dart]: don't do that. Register in main please

**Review by PiotrFLEURY — APPROVED** [review]
