### PR TITLE
Fixed: #273

### LINKED ISSUE #273: Profile page display double email
**Describe the bug**
When the user is authenticated with an email account, the profile page display his email twice

**To Reproduce**
1. Go to the profile page

**Expected behavior**
Display email only once

### PR DESCRIPTION
**Pull request by nathanvandeperre97**

### CODE REVIEW

File: lib/pages/profile.dart [hunk 1]
```diff
@@ -86,20 +86,24 @@ class ProfileState extends State<Profile> {
...
-                              fontSize: 13,
-                              color: WHITE,
+                      user?.displayName != null
+                          ? Container(
+                              height: MediaQuery.of(context).size.height * 0.1,
+                              width: MediaQuery.of(context).size.width,
+                              child: Align(
+                                alignment: Alignment.topLeft,
+                                child: Text(
+                                  user.email,
```
Comment (PiotrFLEURY) [inline lib/pages/profile.dart:96]: souble be user.displayName no ?

**Review by PiotrFLEURY — CHANGES_REQUESTED** [review]

**Review by PiotrFLEURY — APPROVED** [review]
